# Typically, a conversation is formatted with a system message first, 
#   followed by alternating user and assistant messages.
# The system message helps set the behavior of the assistant. 
#   In the example above, the assistant was instructed with “You are a helpful assistant.”
# The user messages help instruct the assistant. 
#   They can be generated by the end users of an application, or set by a developer as an instruction.
# The assistant messages help store prior responses. 
#   They can also be written by a developer to help give examples of desired behavior.

from dataclasses import dataclass, field
from typing import List, Dict


class Role:
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


@dataclass
class Message:
    text: str
    role: str

    def __dict__(self) -> Dict:
        return dict(role=self.role, content=self.text)


@dataclass
class Chat:
    messages: List[Message] = field(init=False, default_factory=list)
    
    def set_system_message(self, text: str):
        self.messages = []
        self.messages.append(Message(role=Role.SYSTEM, text=text))

    def add_message(self, message: Message):
        self.messages.append(message)
    
    @property
    def list(self) -> List[Dict]:
        return [message.__dict__() for message in self.messages]

    

