# Typically, a conversation is formatted with a system message first, 
#   followed by alternating user and assistant messages.
# The system message helps set the behavior of the assistant. 
#   In the example above, the assistant was instructed with “You are a helpful assistant.”
# The user messages help instruct the assistant. 
#   They can be generated by the end users of an application, or set by a developer as an instruction.
# The assistant messages help store prior responses. 
#   They can also be written by a developer to help give examples of desired behavior.

from dataclasses import dataclass, field
from typing import List, Dict

from app.content.prompts import Prompt, DefaultPrompt
from app.models import Model, GPT_3_5


class Role:
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


@dataclass
class Message:
    text: str
    role: str
    tokens: dict = field(default_factory=dict)

    def __dict__(self) -> Dict:
        return dict(role=self.role, content=self.text)


@dataclass
class Chat:
    messages: List[Message] = field(init=False, default_factory=list)
    prompt: Prompt = field(default=DefaultPrompt)
    model: Model = field(default=GPT_3_5)
        
    def add(self, message: Message):
        self.messages.append(message)

    def clean(self):
        self.messages = []
    
    def set_prompt(self, prompt: Prompt):
        self.prompt = prompt
        self.clean()
        self.messages.append(Message(role=Role.SYSTEM, text=prompt.text))

    @property
    def list(self) -> List[Dict]:
        return [message.__dict__() for message in self.messages]

    @property
    def _tokens(self) -> dict:
        return self.messages[-1].tokens if len(self.messages) > 1 else {}

    @property
    def _price(self) -> float:
        price = self.model.price.input * self._tokens.get("prompt_tokens", 0) +\
             self.model.price.output * (self._tokens.get("total_tokens", 0) - self._tokens.get("prompt_tokens", 0))
        normalized_price = round(price / 1000, 4)
        return normalized_price

    @property
    def _first(self) -> str:
        return cut_string(self.messages[1].text) if len(self.messages) > 1 else ""

    @property
    def status(self) -> Dict:
        return dict(
            prompt=self.prompt.name, 
            messages=len(self.messages) - 1,
            model=self.model.name,
            first=self._first,
            tokens=self._tokens,
            price=self._price)
    
    def __post_init__(self):
        # setting default conversation prompt
        self.messages.append(Message(role=Role.SYSTEM, text=self.prompt.text, tokens={}))


def cut_string(string):
    if len(string) > 100:
        string = string[:100] + "..."
    return string
